### ISSUE TITLE
Check notes for check.pass,warn,fail

### ISSUE THREAD

**Issue by stiletto** [silas/node-consul#10]
It should be possible to pass a note for a check when calling
consul.agent.check.pass()
consul.agent.check.warn()
consul.agent.check.fail()
Consul allows you to pass it via query parameters:
https://www.consul.io/docs/agent/http/agent.html#agent_check_pass

**Comment by silas** [comment]
You can now, I seemed to have missed documenting it

Something like the following should work

```
consul.agent.check.fail({ id: 'example', note: 'foo' }, callback)
```
