### ISSUE TITLE
Typos in parameters names of consul watch

### ISSUE THREAD

**Issue by gdoron** [silas/node-consul#101]
While the readme specifies the parameters of consul watch in camelCase, the code that uses them use only lowercase letters.

backoffFactor
backoffMax
maxAttempts

vs

https://github.com/silas/node-consul/blob/master/lib/watch.js#L42

**Comment by silas** [comment]
All parameters are normalized internally to lowercase.

See the `normalizeKeys` call in the linked function:
https://github.com/silas/node-consul/blob/40d9d814d94500fe60cfb9e85809e92d2846897a/lib/watch.js#L26

And it's implementation:
https://github.com/silas/node-consul/blob/40d9d814d94500fe60cfb9e85809e92d2846897a/lib/utils.js#L51-L63

Feel free to re-open if something else isn't working.
