### ISSUE TITLE
HTTP keepalive is disabled by default - Document how to enable http keepalive for consul?

### ISSUE THREAD

**Issue by TysonAndre** [silas/node-consul#113]
It seems as if https://github.com/silas/node-consul/blob/main/lib/consul.js uses https://www.npmjs.com/package/papi , which documents that 

> Advanced options
>
> - agent (http.Agent|https.Agent, optionals): if not set uses the global agent

https://nodejs.org/api/http.html#http_new_agent_options notes that the global agent will disable keepalive by default

> keepAlive <boolean> **Keep sockets around even when there are no outstanding requests, so they can be used for future requests without having to reestablish a TCP connection.** Not to be confused with the keep-alive value of the Connection header. The Connection: keep-alive header is always sent when using an agent except when the Connection header is explicitly specified or when the keepAlive and maxSockets options are respectively set to false and Infinity, in which case Connection: close will be used. Default: false.

The documentation of http.Agent and https.Agent mention how this is done (the one to use depends on whether the scheme is http:// or https://)

> The default http.globalAgent that is used by http.request() has all of these values set to their respective defaults.
> 
> To configure any of them, a custom http.Agent instance must be created.
> 
> ```
> const http = require('http');
> const keepAliveAgent = new http.Agent({ keepAlive: true });
> options.agent = keepAliveAgent;
> http.request(options, onResponseCallback);
> ```

NOTE: For anyone looking at this issue, http.Agent is not to be confused with https://github.com/silas/node-consul#consulagent , those are completely different things.

**I think that passing `new Consul({ host, port, agent: keepAliveAgent })` would be how this is done?**

Use case
-----------

Consider an application that connects to consul and fetches 20 groups of keys serially at startup. When http keepalive is disabled, then I assume that

- dns.lookup will be called 20 times (if it is not an ip address, this would be resolved either after a while (a hostname), or on the next tick(locally) instead of immediately)
- a TCP connection will be created 20 times
- 20 requests will be made (expected)
- a TCP connection will get closed 20 times

This would result in worse performance and longer startup time if the consul agent is not running on localhost (and possibly may still be worse even if it is on localhost).

If there are multiple modules that use consul that are initialized serially, they may get a benefit from reusing connections that were already established.
- e.g. `await module1.init(); await module2.init(); await module3.init();`

(I'm still looking into whether this is actually an issue or a symptom of connection errors - EDIT: The application should really be rewritten to avoid excessively calling consul, it was a non-standard wrapper of node-consul improperly using Watches, or watching keys redundantly)

This may also be useful for avoiding spurious errors in consul.watch calls

Alternatives
--------------

It may make sense to enable keepalive by default in some future release

In some projects, I've seen https://www.npmjs.com/package/agentkeepalive used, which has features such as "Add free socket timeout: avoid long time inactivity socket leak in the free-sockets queue."

Questions
-------------

1. Is there a reason specific to consul to avoid keep alive?
2. Would this cause issues with consul.Watch - I haven't looked into this but assume the timeout would be handled by custom agents

**Comment by silas** [comment]
Yes, passing `agent` in the options as specified is the correct method to use a different agent, something like:

``` javascript
const agent = new require('http').Agent({ keepAlive: true });  // or require('https') if you are using https
const consul = require('consul')({ agent });
```

should work.

The answer to your questions at the end are 1) nope and 2) I wouldn't think so.

It looks like upstream might make this the default in the near-ish future, but might be worth just doing it in this project beforehand. 

I'll either do that or document how to enable keepalives.
