### ISSUE TITLE
`lock` function mentioned in README is not available

### ISSUE THREAD

**Issue by kadishmal** [silas/node-consul#12]
There is this [`consul.lock()`](https://github.com/silas/node-consul#lock) which is not available actually. Does anybody know where it's gone?

**Comment by silas** [comment]
It's not in a released version yet. I'll take a look at releasing it this weekend and close this ticket when I do.

**Comment by silas** [comment]
I released version 0.15.0 to npm, although I marked `consul.lock` as experiment in the README for now.
