### ISSUE TITLE
access to keys response

### ISSUE THREAD

**Issue by jdmarshall** [silas/node-consul#123]
The consul docs suggest that the most recent ModifyIndex for a group of keys is returned as a header in the repsponse.

Is there a way to get access to the http request?

**Comment by silas** [comment]
In the currently published version `0.40.0` the full response is available in the callback interface via the third parameter:

```javascript
const consul = require('consul')();

consul.agent.self((err, body, res) => {
  console.log(res.headers);
});
```

It's not available in the promise interface.

The currently unreleased version is promise based and supports exposing the raw response, but the interface is not stable yet.

**Comment by silas** [comment]
You can get access to this header in v1.0.0 using the following syntax:

```javascript
const events = require('events');
const Consul = require('consul');

async function main() {
  const consul = new Consul();

  const ctx = new events.EventEmitter();
  ctx.includeResponse = true;

  const [res, data] = await consul.agent.self({ ctx });

  console.log(res.headers);
}

main();
```

**Comment by jdmarshall** [comment]
Congratulations on 1.0.0

Can't wait to break it :D
