### ISSUE TITLE
TypeScript Support for consul.query

### ISSUE THREAD

**Issue by StefanTurbine** [silas/node-consul#131]
Hello there,

I am trying to integrate the prepared statements of your consul client into a typescript application.
Sadly the types seem to not include the query part of your client. Am I using the wrong Types here or is this a bug worth fixing?
The following versions are being used:

- consul: ^1.1.0
-  @types/consul: ^0.40.0

![image](https://user-images.githubusercontent.com/10639166/195320084-ae225680-485f-47d7-966d-ced969645f90.png)

**Comment by silas** [comment]
As mentioned the types are maintained in DefinitelyTyped and I've never contributed to it. I created a general ticket to track adding TypeScript support to this repository (see https://github.com/silas/node-consul/issues/142).
