### ISSUE TITLE
Reset index of watch job if index ever decreases

### ISSUE THREAD

**Issue by brandonw** [silas/node-consul#135]
> Reset the index if it goes backwards.
> While indexes in general are monotonically increasing(i.e. they should only ever increase as time passes), there are several real-world scenarios in which they can go backwards for a given query. Implementations must check to see if a returned index is lower than the previous value, and if it is, should reset index to 0 - effectively restarting their blocking loop. Failure to do so may cause the client to miss future updates for an unbounded time, or to use an invalid index value that causes no blocking and increases load on the servers. Cases where this can occur include:
> ...

https://developer.hashicorp.com/consul/api-docs/features/blocking#implementation-details

**Comment by silas** [comment]
Thanks for reporting this.

I think consul represents the index has a `uint64`, so we won't be able to just parse it as a number. I think we'll either need to use `BigInt` or do the checks on the string.s It looks like `BigInt` is supported in Node `10.4.0+`, so that's probably fine.
