### ISSUE TITLE
Can't invoke "new Consul()" constructor in typescript app

### ISSUE THREAD

**Issue by nikasakandelidze** [silas/node-consul#138]
Hey there!
So i'm playing with NestJS app right now with typescript and consul(V1.2) and have next error:
![image](https://user-images.githubusercontent.com/60848556/208268191-c5704915-6269-43b0-b44b-35df0e4480b1.png)

This is all while using typescript and using explicit "import" statement and not require like:
`import Consul from 'consul'`
And when i switched it to:
`const consul = require('consul')`
 it worked like a charm.
Could someone explain what is the reason for it?
Thanks in advance.

**Comment by silas** [comment]
This library currently uses commonjs and exports a class by default (probably a mistake on my part), which can cause issues with the default typescript options.

You can probably fix this by setting [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop) to `true`. If that doesn't work feel free to reopen, but include your full `tsconfig.json`.
