### ISSUE TITLE
Typescript support for client.watch

### ISSUE THREAD

**Issue by InNOcentos** [silas/node-consul#140]
Hello,

Typescript does not allow me to use some additional options for methods, which actually has this options. Adding @ts-ignore solves the problem.

Using these versions:
- consul: ^1.2.0
- @types/consul: ^0.40.0

![Снимок экрана 2022-12-21 в 14 02 50](https://user-images.githubusercontent.com/46030908/208891255-a6e29ad2-4fb0-4fdf-9cc7-529750ecfab6.png)

![Снимок экрана 2022-12-21 в 14 08 47](https://user-images.githubusercontent.com/46030908/208891465-6930bc75-da7d-4243-8bc5-f4bf68a03549.png)

**Comment by silas** [comment]
As mentioned the types are maintained in DefinitelyTyped and I've never contributed to it. I created a general ticket to track adding TypeScript support to this repository (see #142).
