### ISSUE TITLE
Typescript suppor for grpc healthcheck's

### ISSUE THREAD

**Issue by InNOcentos** [silas/node-consul#141]
Hello,

Typescript does not allow me to use grpc transport for healthchecks, which is actually documented and works well with @ts-ignore.

Using these versions:

    consul: ^1.2.0
    @types/consul: ^0.40.0

![Снимок экрана 2022-12-21 в 14 12 19](https://user-images.githubusercontent.com/46030908/208892086-6977cead-2081-4224-88f5-14fa66049716.png)

![Снимок экрана 2022-12-21 в 14 15 14](https://user-images.githubusercontent.com/46030908/208892605-a24c5b9a-2b68-483f-850a-fc643c7c7195.png)

**Comment by silas** [comment]
As mentioned the types are maintained in DefinitelyTyped and I've never contributed to it. I created a general ticket to track adding TypeScript support to this repository (see #142).
