### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by silas** [silas/node-consul#142]
TypeScript support is currently maintained in [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Consider providing TypeScript definitions in this repository.

I probably won't have time to do this anytime soon, so if someone wants to take this on feel free to open a PR (or submit fixes to DefinitelyTyped).

**Comment by czy88840616** [comment]
Do you have plans to rewrite in typescript?

**Comment by silas** [comment]
I don't have any immediate plans. I'll probably do it at some point, but I don't have any free time at the moment.
