### ISSUE TITLE
extend host:port to support multiple agents

### ISSUE THREAD

**Issue by matthiasschoger** [silas/node-consul#149]
Currently only one host:port is supported.

It would be great if a list of host:ports could be entered if Consul is running in cluster mode.
In that case, the next host:port from the list should be used if the current node is or goes down.

**Comment by silas** [comment]
Looking at the Go API client it seems like they're against this:
 * https://github.com/hashicorp/consul/issues/1232
 * https://discuss.hashicorp.com/t/how-to-make-a-client-for-multiple-hosts/29617

If they end up adding this to the Go client I'd consider replicating the functionality here, but I think it's better to just follow their lead around how API clients should work.

It seems like you're best bet is to 1) put consul behind a load balancer or 2) handle the failover logic in your application.

**Comment by matthiasschoger** [comment]
Sorry, I probably didn’t make myself clear. 

I was proposing for the client to have one connection to one Consul agent from the list. 
Only if that agent goes down or is unavailable, the client should select another agent from the list.

**Comment by silas** [comment]
Yeah, that's what I understood you to mean.

What "down or ... unavailable" means is pretty complicated, and the experience is going to be bad in all but the most trivial cases (e.g. DNS doesn't resolve, DNS times out, HTTP port not open, HTTP times out, TLS certificate invalid, Consul no longer a member of the cluster, etc...).

If you have a definition of what down or unavailable means to you it should be pretty easy to create a wrapper for the client to handle those cases. If you don't want to do that setting up a load balancer is probably going to be the most reliable solution.

**Comment by matthiasschoger** [comment]
Just read the comment on the Consul thread in detail, and I think I understand better now.

Seems like the recommendation is to connect the the local Consul agent by default. Makes sense and should cover my use-case.
Closing this issue.
