### ISSUE TITLE
Lock Issues

### ISSUE THREAD

**Issue by ekristen** [silas/node-consul#16]
I had to comment out https://github.com/silas/node-consul/blob/master/lib/lock.js#L307-L315 and https://github.com/silas/node-consul/blob/master/lib/lock.js#L232-L235 to get the lock system to work reliably. 

I found that the monitor updates code is broken and the time is always going to fail, so basically after 15 seconds ( the default) it will always release the lock.

I also found that the data.Flags would always fail on subsequent restarts of the application to check the lock. 

By commenting out those two portions, the locking systems seems to work reliably for me now.

**Comment by ekristen** [comment]
@silas thoughts?

**Comment by silas** [comment]
Yeah, there is definitely an issue there. I'll take a look this weekend and try to get it sorted out.

**Comment by ekristen** [comment]
You can take a look at my fork, I fixed it so it works, but it might not be the "proper" fix.

**Comment by silas** [comment]
Want to try version `0.18.1` and let me know if that fixes (fbaf4dc) the monitor issue.

I haven't been able to reproduce the `data.Flags` problem, can you give me some more info on your setup (consul version, server arch, etc...).

**Comment by ekristen** [comment]
I will give it a try. 

I'm using the latest consul version. Most of my testing has been done in a 3 server cluster architecture.

**Comment by ekristen** [comment]
@silas I think you should look at my fork. With 0.18.1, it takes like 30 seconds to get a lock when no lock or session is there. It seems to be you are doing a lot of extra stuff that doesn't need to be.

**Comment by silas** [comment]
If you're still seeing this issue please re-open.

Thanks,
