### ISSUE TITLE
Consul.health.service() functionality does not match documentation

### ISSUE THREAD

**Issue by TheEnvironmentalist** [silas/node-consul#17]
According to the README, `consul.health.service()` works as follows:

>### consul.health.service(options, callback)
>
>Returns the nodes and health info of a service.
>
> Options
>
> * service (String): service ID
> * dc (String, optional): datacenter (defaults to local for agent)
> * tag (String, optional): filter by tag
> * passing (Boolean, optional): restrict to passing checks
>
>Usage
>
>``` javascript
>consul.health.service('example', function(err, result) {
>  if (err) throw err;
>});
>```
>
>Result
>
>``` json
>[
>  {
>    "Node": {
>      "Node": "node1",
>      "Address": "127.0.0.1"
>    },
>    "Service": {
>      "ID": "example",
>      "Service": "example",
>      "Tags": [],
>      "Port": 0
>    },
>    "Checks": [
>      {
>        "Node": "node1",
>        "CheckID": "service:example",
>        "Name": "Service 'example' check",
>        "Status": "critical",
>        "Notes": "",
>        "Output": "",
>        "ServiceID": "example",
>        "ServiceName": "example"
>      },
>      {
>        "Node": "node1",
>        "CheckID": "serfHealth",
>        "Name": "Serf Health Status",
>        "Status": "passing",
>        "Notes": "",
>        "Output": "Agent alive and reachable",
>        "ServiceID": "",
>        "ServiceName": ""
>      }
>    ]
>  }
>]
>```

However, according to the [Consul documentation for the API command it uses](http://www.consul.io/docs/agent/http/health.html), the parameter used isn't actually `serviceID`, it's `name`:

>###  /v1/health/service/
>
>This endpoint is hit with a GET and returns the nodes providing the service indicated on the path. By default, the datacenter of the agent is queried; however, the dc can be provided using the "?dc=" query parameter.

>By default, all nodes matching the service are returned. The list can be filtered by tag using the "?tag=" query parameter.

>Providing the "?passing" query parameter, added in Consul 0.2, will filter results to only nodes with all checks in the passing state. This can be used to avoid extra filtering logic on the client side.

>This endpoint is very similar to the /v1/catalog/service endpoint; however, this endpoint automatically returns the status of the associated health check as well as any system level health checks. This allows a client to avoid sending traffic to nodes that are failing health tests or reporting warnings.

>Users can also build in support for dynamic load balancing and other features by incorporating the use of health checks.

>It returns a JSON body like this:

>```
> [
>  {
>    "Node": {
>      "Node": "foobar",
>      "Address": "10.1.10.12"
>    },
>    "Service": {
>      "ID": "redis",
>      "Service": "redis",
>      "Tags": null,
>      "Port": 8000
>    },
>    "Checks": [
>      {
>        "Node": "foobar",
>        "CheckID": "service:redis",
>        "Name": "Service 'redis' check",
>        "Status": "passing",
>        "Notes": "",
>        "Output": "",
>        "ServiceID": "redis",
>        "ServiceName": "redis"
>      },
>      {
>        "Node": "foobar",
>        "CheckID": "serfHealth",
>        "Name": "Serf Health Status",
>        "Status": "passing",
>        "Notes": "",
>        "Output": "",
>        "ServiceID": "",
>        "ServiceName": ""
>      }
>    ]
>  }
>]
>```
>
>This endpoint supports blocking queries and all consistency modes.

Note the line
> This endpoint is hit with a GET and returns the nodes providing the service indicated on the path.

This caused a few minutes of confusion as I was trying to use `consul.health.service()` to test the health of a specific instance of a service by id. The documentation here says that is what it does, but the documentation for Consul says that it returns the health of _all_ instances of the service by service name.

**Comment by silas** [comment]
Thanks for the report!

And sorry for taking so long to address it.

**Comment by TheEnvironmentalist** [comment]
Absolutely

Date: Sat, 5 Dec 2015 08:43:32 -0800
