### ISSUE TITLE
consul.watch + consul.event.list seems to be broken

### ISSUE THREAD

**Issue by ekristen** [silas/node-consul#24]
This does not seem to work very consistently.

While using `consul watch -type event echo "event"` first every time an even is received, doing the same with node-consul results in inconsistent behavior.

Sometimes the `change` event will fire, other times it will not, if I manually trigger 10 events, generally node-consul will fire `change` on the first, and then it could do it on the next or after I've fired 10 events and then `change` will be fired and contain all the events I triggered.

**Comment by ekristen** [comment]
Further context, it seems like the watch routine goes into a death spin, basically under a certain set of conditions, the `_run` function starts getting called thousands of times and when that happens, it no longer seems to be able to grab new events. 

I've seen it where it never exits the loop, and other times when it does, if it does manage to exit the loop then that is when I see it emit `change` with all the new events.

**Comment by ekristen** [comment]
It appears the the `x-consul-index` values can be vastly different. According to my local tests, during this behavior I'm seeing the index, prevIndex lengths end up being different, and somehow the recorded prevIndex ends up being less than x-consul-index, which causes the death spin of requests, like in the 2 ms range, normally on a local consul instance when the indexes are incrementing then requests usually take like 5s.

**Comment by ekristen** [comment]
Example, some how newIndex is getting set to `799265815391290200` while the old index is `7633490683486594000`, there is a zero missing on the end, not really sure how this is happening, it is very odd, then subsequent request will be something like x-consul-index `799265815391290247` which is missing a 0 on the end.

**Comment by ekristen** [comment]
it seems that if I do a simple diff, return index !== prevIndex things seem to work better.

**Comment by ekristen** [comment]
I can open a PR but this seems to fix my issues and with a slight alteration tests pass https://github.com/ekristen/node-consul/commit/4056a5eca4ce92e7674ef0f44ebd035867660ba1

**Comment by silas** [comment]
Super weird, but it looks like that's what upstream does:

https://github.com/hashicorp/consul/blob/master/watch/plan.go#L77-L93

I wonder why the deep compare is there, don't love that at all.

**Comment by silas** [comment]
Published in version 0.23.0

Thanks for the report and fix!
