### ISSUE TITLE
Missing Consul watches (type: services) html to watch for service changes

### ISSUE THREAD

**Issue by wreuven** [silas/node-consul#25]
Missing https://www.consul.io/docs/agent/watches.html.

Specifically, I need type: services in order to watch for service changes.

More specifically, I'd like my client to know as soon as the service it is using fails a health check without having to poll. Perhaps there is an alternate way to do this that I am missing?

**Comment by silas** [comment]
Watch is already implemented, see the [docs](https://github.com/silas/node-consul#watch) and #26 for some examples
