### ISSUE TITLE
how can i watch service and keyprefix?

### ISSUE THREAD

**Issue by jippi** [silas/node-consul#26]
Based on the docs and code i can't find a way to watch something that isn't just a normal `kv`

am I missing something? :)

**Comment by silas** [comment]
So you can pass pretty much any existing method and options into watch.

Method is just one of the methods define in the docs and options is just any the parameters is accepts.

Example: watch service list
``` javascript
var watch = consul.watch({
  method: consul.catalog.service.list,
  options: {}
});
```

Example: watch service nodes
``` javascript
var watch = consul.watch({
  method: consul.catalog.service.nodes,
  options: { service: 'example' }
});
```

Example: watch kv prefix (recursive)
``` javascript
var watch = consul.watch({
  method: consul.kv.get,
  options: { key: 'example', recurse: true }
});
```

Feel free to re-open if that doesn't make sense.

**Comment by jippi** [comment]
Hi @silas - got everything working on my own like that, except `keyprefix` - can't find anything in the source for that

what I ended up doing was something like this, which seem to work - my JS skills are terrible, so feel free to adopt or whatever :) 

````
var utils = require('../../../node_modules/consul/lib/utils.js');

export function getKeyPrefixHandler(opts, callback) {
  if (typeof opts === 'string') {
      opts = { prefix: opts };
    }

    var req = {
      name: 'kv.prefix',
      path: '/kv/{prefix}',
      params: {
        type: "keyprefix",
        prefix: (opts.prefix || '')
      },
      query: {},
    };

    req.query.recurse = true;

    if (opts.raw) {
      req.query.raw = 'true';
      req.buffer = true;
    }

    utils.options(req, opts);

    this.consul._get(req, function(err, res) {
      if (res && res.statusCode === 404) return callback("Key prefix '"+ opts.prefix + "' does not exist", undefined, res);
      if (err) return callback(err, undefined, res);
      if (opts.raw) return callback(null, res.body, res);

      if (res.body && Array.isArray(res.body) && res.body.length) {
        res.body.forEach(function(item) {
          if (!item.hasOwnProperty('Value')) {
            return;
          }
          item.Value = utils.decode(item.Value, opts);
        });
      } else {
        return callback(undefined, undefined, res);
      }

      if (!req.query.recurse) return callback(null, res.body[0], res);

      callback(null, res.body, res);
    });
}
````

**Comment by jippi** [comment]
your example with kv recurse, doesn't seem to match the consul docs

````json
{
  "type": "keyprefix",
  "prefix": "foo/"
}
``` 

as you would be sending `key` instead of `prefix` - and `type` `key`instead of `keyprefix`

**Comment by silas** [comment]
@jippi I think `type` is just a construct of the Golang API and the consul client. If you look at [the consul source](https://github.com/hashicorp/consul/blob/42aa817456910bdd7c37f496f151c3037eabf5cc/watch/watch.go#L70) you'll see it's just used for picking the parameters to send to the server.

Here is the HTTP result of the follow command:

```
$ consul watch -type keyprefix -prefix=test echo reload
```

![requests](https://cloud.githubusercontent.com/assets/18528/13414581/eafe6e6a-df21-11e5-8268-b8cfd36b48f0.png)

Watches are better described in regards to the HTTP API under "Blocking Queries" via https://www.consul.io/docs/agent/http.html

**Comment by jippi** [comment]
ok :)
