### ISSUE TITLE
docker interval support

### ISSUE THREAD

**Issue by OferE** [silas/node-consul#27]
Hi,
In the register service. is there a support for the docker + interval feature of consul?

Thanks,
Ofer

**Comment by silas** [comment]
I published version `0.24.0` to npm which now supports this feature.

``` javascript
var consul = require('consul')();

var check = {
  name: 'docker-test',
  script: 'true',
  interval: '30s',
  dockercontainerid: 'c9efabab870d',
  notes: 'This runs in a Docker container.',
};

consul.agent.check.register(check, function(err) {
  if (err) throw err;
});
```

FYI: There seems to be a bug with Consul and Docker 1.10 which was just fixed a couple of hours ago and hasn't been released, see https://github.com/hashicorp/consul/issues/1706

Thanks for the bug report!
