### ISSUE TITLE
catalog.list.service vs catalog.list.services

### ISSUE THREAD

**Issue by OferE** [silas/node-consul#35]
It seems that the API is missing getting a status on a specific service.
It also seems the the correct api should be catalog.list.service.
Currently this api is providing list of all services which should be a different api call... (catalog.list.services)

**Comment by OferE** [comment]
found the relevant apis - naming are confusing...

**Comment by Cidaas** [comment]
@OferE  can you please specify , what is the correct api to details of specific service?
