### ISSUE TITLE
KV Value not a string

### ISSUE THREAD

**Issue by Zambonilli** [silas/node-consul#36]
Is there a way to get the Value of a key value pair to not be a string?  IE: I add a key value pair foo with value 10.  It looks like the client will receive the value "10".  I'm going down the path of using a Joi schema for all of our Key value pairs but I wanted to double check there isn't something built in already with consul and node-consul.

**Comment by silas** [comment]
Sorry, gotten super behind on my open source projects. As you probably figured out there is nothing built into consul. The client supports strings and buffers, if you want typed data I'd just `JSON.stringify`/`JSON.parse`
