### ISSUE TITLE
[Feature] filter for healthy nodes at consul.catalog.service.nodes

### ISSUE THREAD

**Issue by xFragger** [silas/node-consul#43]
If you agree with me and think this is usefull, i would provide a PR for that

**Comment by silas** [comment]
I think using [prepared queries](https://www.consul.io/docs/agent/http/query.html) with `OnlyPassing` is probably a better approach than adding the same type of functionality into this library.

The interface is a little more complex, but it's going to be more efficient and has a lot of other nifty features.

https://github.com/silas/node-consul#query
