### ISSUE TITLE
Get QueryMeta with KV request

### ISSUE THREAD

**Issue by ziyasal** [silas/node-consul#44]
Consul [go api providing](https://github.com/hashicorp/consul/blob/master/api/kv.go#L157) [QueryMeta](https://github.com/hashicorp/consul/blob/9fc0c0ede2299bc290c0d5ab4d316788b605a197/api/api.go#L69) it would be good to implement in this package

**Comment by silas** [comment]
I couldn't think of a classy interface that was backwards compatible, so I just created a helper method for parsing the http response.

``` javascript
consul.kv.get('one', function(err, body, res) {
  if (err) throw err;
  console.log(consul.parseQueryMeta(res));
});
```

Results

```
{ LastIndex: '14', LastContact: 0, KnownLeader: true }
```

**Comment by ziyasal** [comment]
hi @silas  thanks for quick update 👍
