### ISSUE TITLE
Setting the http-addr option on consul.watch

### ISSUE THREAD

**Issue by timcrall** [silas/node-consul#46]
How can I override the default of 127.0.0.1:8500 as the address of the consul agent on a watch command?

In the Consul cli, there is a -http-addr option, but the below code does not seem to work (I still see the watch attempting to connect to 127.0.0.1:8500)

`
var watch_options = {  'type' : 'services', 'datacenter' : 'ord', 'http-addr' : '100.78.239.21:8500'};
console.log ("Trying to reach agent ", watch_options["http-addr"]);

var watch = consul.watch({ method: consul.catalog.service.list, options: watch_options});

 watch.on('change', function (data, res) {
    	console.log ("BOOM");
    	console.log('data:', data);
    });
`

**Comment by timcrall** [comment]
Not sure why the code-block formatting only kind of worked in the above post...

**Comment by silas** [comment]
You need to set the host/port when you [create](https://github.com/silas/node-consul#init) the consul client, example:

``` javascript
var consul = require('consul')({host: 'example.org', port: 8500});

var watch = consul.watch({ method: consul.kv.get, options: { key: 'test' }});
```

**Comment by timcrall** [comment]
Thanks!
