### ISSUE TITLE
Using a token on lock

### ISSUE THREAD

**Issue by timcrall** [silas/node-consul#47]
Is it possible to set the 'key' option on a lock operation?

I'm trying to do the equivalent of

`consul lock -name='ConsulSync' -pass-stdin -token=$TOKEN service/us/locks/foo child_command`  

My code is

```
var lock_options = {  key : 'service/us/locks/foo',
                      name : 'ConsulSync',
                      token : process.env.TOKEN
                   };

var lock = consul.lock(lock_options);
```

but I'm getting a 403 "rpc error: Permission denied"

Also, can I set 'pass-stdin'?

**Comment by silas** [comment]
Good call, I'll try  to get this fixed in the next couple of days.

As a work around, if you don't mind using the same token for all your calls you can set it as a default.

``` javascript
var consul = require('consul')({ defaults: { token: 'mytoken' } });

var lock = consul.lock({ key: 'test' });
```

**Comment by timcrall** [comment]
That should work for me.  Thanks.
