### ISSUE TITLE
No lock in use

### ISSUE THREAD

**Issue by timcrall** [silas/node-consul#48]
Sorry to be a pest....

My code is almost working perfectly now - it went through several 'watch' and 'lock' events perfectly - but then it got an error.  It looks like a lock.release() caused an error because somehow there was no lock?  But the lock.release() is called only within the lock.on('acquire' callback.

```
/usr/src/app/node_modules/consul/lib/lock.js:110
  if (!self._ctx) throw errors.Validation('no lock in use');
                  ^

Error: no lock in use
    at create (/usr/src/app/node_modules/consul/lib/errors.js:14:5)
    at Object.validation (/usr/src/app/node_modules/consul/lib/errors.js:26:15)
    at Lock.release (/usr/src/app/node_modules/consul/lib/lock.js:110:32)
    at /usr/src/app/src/main/node/agent.js:40:18
    at /usr/src/app/src/main/node/catalog.js:32:5
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

```
  var watch = consul.watch({ method: consul.catalog.service.list, options: this.watch_options});

  watch.on('change', function (data, res) {

  	that.health.setWatch ("UP");

    var lock = consul.lock(that.lock_options);

    lock.on('acquire', function(){
        that.health.setLock ("UP");
        var catalog = new Catalog(that.health);
        catalog.update(data, function(){
            lock.release();
        });
    });

    lock.on('error', function(err){
        console.log ("ERROR: Consul Lock Error");
        console.log (JSON.stringify(err, null, 4));
        that.health.setLock ("ERROR");
    });

    lock.acquire();
  });

  watch.on('error', function (err) {
    console.log ('ERROR: Consul Watch Error');
    console.log (JSON.stringify(err, null, 4));
    that.health.setWatch ("ERROR");
  });
```

**Comment by timcrall** [comment]
Putting the lock.release() in a try/catch has helped somewhat - I still get the error periodically, but the program continues running regardless...

**Comment by silas** [comment]
So there are a couple of possible issues.

First, you're not monitoring the status of the lock, you need to have a callback on `lock.on('end',`. Once that is emitted you no longer have a lock on the resource and you can't call release.

Second, you can only call `lock.release` once and you can only call it if you have an acquired lock. It throws the error you mentioned because when you called it you no longer had a lock. This could happen because of a session timeout or because you called `release` more than once.

If `catalog.update` triggers a callback more than once you'd get this error.

``` javascript
var locked = false;

var lock = consul.lock(that.lock_options);

lock.on('acquire', function(){
    locked = true;
    var catalog = new Catalog(that.health);
    catalog.update(data, function(){
        if (locked) lock.release();
    });
});

lock.on('error', function(err){
    console.log(err);
});

lock.on('end', function(err){
    locked = false;
});

lock.acquire();
```

**Comment by timcrall** [comment]
Ok - I don't really understand, though, how the 'acquire' callback would
get called if there wasn't still a lock?  Any by the very definition of a
lock, I would think I wouldn't be able to have more than one (on the same
key) acquired at a time?

I guess you're saying that the lock could expire between the time when
'acquire' was called and when the callback from the child process
completed?  Ok, I suppose that makes sense...and that would then invoke
'end'?  And also, I think, 'error'?  So do I really need 'end' or could I
just use 'error'?

Also, related, is timeout a valid option for lock options?  Because even
setting timeout to 60*60*1000 (1 hour), I'm getting frequent timeouts (and
they certainly don't take an hour to timeout, either...)

Thanks again
