### ISSUE TITLE
Support transactions

### ISSUE THREAD

**Issue by maxnasonov** [silas/node-consul#50]
Hello,

Any plans on subject:
https://www.hashicorp.com/blog/consul-0-7.html#txn
?

Thank you for the project anyway.

**Comment by ecourreges-orange** [comment]
This would be of great use for git2consul which currently sends as many PUT as there are keys to update, so nothing is atomic so far. Using /txn in one big transaction would fix that.

I suppose it could be added with methods like
consul.kv.txn.set(), consul.kv.txn.delete() to prepare the json and **consul.kv.txn.send()** to send it?

Regards.

P.S: I am hesitating between rewriting a git2consul more suitable for my needs in python, or making changes to node-consul and git2consul. The latter would benefit the community more I suppose.
