### ISSUE TITLE
Consul watcher never emits 'error' event if connection to consul is lost

### ISSUE THREAD

**Issue by SkeLLLa** [silas/node-consul#51]
Hello. I'm using consul client for service discovery.  My code looks like:
```js
const consulCli = require('consul');
const Promise = require('bluebird');

const client = consulCli({
  host,
  port,
  promisify: Promise.fromCallback
});

const options = {
  service: 'my-service-name'
};

client
      .watch({
        method: client.catalog.service.nodes,
        options,
        wait: '2m'
      })
      .on('change', (data) => {
        console.log('CHANGE');
      })
      .on('error', (err) => {
        console.log('ERROR');
      });
```

I run this code locally on my machine and consul is running on remote machine. When network connection is up, changes coming (it logs `CHANGE`). But when I shutdown my network connection consul client never steps into neither change event, nor in error event.

Such behavior only appear when network disconnect happens after establishing consul client connection (line `const client = consulCli({`).

Steps 2 reproduce:
* Connect to consul via `consul` client library
* Create watcher via client
* Wait some time
* Disconnect from network
* See result - no error event emitted

Also when I enable connection again consul client never receive nether change nor error event. It looks like it's getting stuck somewhere inside request.

If consul host is already down `papi` lib throws timeout exception and it's handled well.

UPD: Seems it happens not always. Also specifying defaults with timeout seems resolves this issue (but I think that some timeout should be set by default to value passed in `wait` + some seconds.

**Comment by silas** [comment]
Sorry for not getting this fixed earlier, and thanks for the detailed issue report.

**Comment by jdmarshall** [comment]
I don't know if this is related, but I see a similar problem with kv.get(). I'm wondering if the problem is in get and got fixed in the wrong spot.

**Comment by jdmarshall** [comment]
@SkeLLLa  You don't happen to know what version of consul this issue was introduced do you? Asking for a friend.
