### ISSUE TITLE
Add semaphore support

### ISSUE THREAD

**Issue by seawatts** [silas/node-consul#52]
It seems like the `lock` method almost gets you there. However the lock method does not provide a limit which is key for having the semaphore work.

https://www.consul.io/docs/guides/semaphore.html
https://godoc.org/github.com/hashicorp/consul/api#Semaphore

**Comment by silas** [comment]
Hey, sorry @seawatts for not getting back to you sooner. I'm probably not going to implement semaphore and I'll probably end up deprecating/removing lock. I haven't had much success creating a good interface for these locking algorithms in node and they add a lot of complexity to the library that very few people actually need.

Thanks for the interest though.
