### ISSUE TITLE
Support of tls_skip_verify for Healthchecks

### ISSUE THREAD

**Issue by md2k** [silas/node-consul#53]
Hi @silas can you please add subject, because this is supported since Consul v0.5 and can be very useful and remove requirements to use external scripts to avoid errors.
https://github.com/hashicorp/consul/blob/a533e255ab7740da4c476e2be8820245c4914d5a/command/agent/config.go#L1155-L1175

**Comment by silas** [comment]
Thanks for reporting!

Fixed in consul@0.28.0
