### ISSUE TITLE
lock kv.get request timeout is too sensitive and causing random request timeout

### ISSUE THREAD

**Issue by shlompy** [silas/node-consul#57]
The default request timeout for a lock kv.get request which is being set is too sensitive for some environments - lockwaittime +1000ms.
This is causing random timeout errors which are emitting 'end' event for the lock.

Changing this to +5000ms seems to fix my issues, so I've opened a PR with a fix to expose the request timeout to the lock() options.

https://github.com/silas/node-consul/pull/56

**Comment by shlompy** [comment]
#56

**Comment by silas** [comment]
I pushed `consul@0.29.0` which has `lockwaittimeout`, which uses a relative time. You should be able to set it to `5s` or `5000`. I decided to hold of on documenting it until I can rewrite all the `consul.lock` documentation.

**Comment by shlompy** [comment]
thanks!
I see the new 0.29 version in npm!
Much appreciated!

**Comment by grempe** [comment]
> I decided to hold of on documenting it until I can rewrite all the consul.lock documentation.

Updated docs that describe all of the lock features, and the interplay between them, would be most excellent for me right about now. 🥇

**Comment by silas** [comment]
Yeah, agreed. I'll probably end up renaming it to something like electLeader, which better describes what it actually does. In all honesty it's pretty hard to use correctly and I haven't been able to figure a better API. I'm definitely open to suggestions.

I've basically given up on using node/javascript for this type of stuff and stick with Go these days :/
