### ISSUE TITLE
`consul.kv.get('string')` fetches more than exact match

### ISSUE THREAD

**Issue by eyalzek** [silas/node-consul#60]
Lets say I have to following keys:
`foo/bar` & `foo-test/bar`

fetching the keys like so:
`consul.kv.get({'key': 'foo', recurse:true}, function(err,kvs,res) {console.log(kvs);});`

would fetch both keys. I'm not sure if this is expected or not? one solution on my side would be to append a `/` to the key name, but again, I'm not sure if this should be solved on the client side.

**Comment by silas** [comment]
Yes, that is the expected results. Consul doesn't supported directory style listing via the recurse option.

Let's say you have the following keys
 - `test/a`
 - `test/b`
 - `test/b/foo`
 - `test/b/bar`
 - `test/c`

You can use the `consul.kv.keys` method to get something similar to directory style listing.

```
consul.kv.keys({ key: key, separator: '/' }, function(err, data) {
  if (err) throw err;
  console.log(key, '=>', data);
});
```

```
test/ => [ 'test/a', 'test/b', 'test/b/', 'test/c' ]
test/b/ => [ 'test/b/bar', 'test/b/foo' ]
```

Notice that your input key must having a trailing `/` and that you results will include sub-keys (indicated by the trailing `/`).
