### ISSUE TITLE
Inconsistent type for port field

### ISSUE THREAD

**Issue by TobyColeman** [silas/node-consul#61]
When creating a new instance of Consul, the port type is a [string](https://github.com/silas/node-consul#consuloptions). However, when registering a new service the port type is a [number](https://github.com/silas/node-consul#consulagentserviceregisteroptions-callback).

This makes extending the typings for this module a little awkward, see:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/consul/index.d.ts#L263

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/consul/index.d.ts#L990

**Comment by silas** [comment]
If you send a number to consul options it should work fine assuming you're not sending `0`, does that not work? What do you suggest changing, just setting the `|| '8500'` to a number of something?

**Comment by TobyColeman** [comment]
Sorry, I should have probably clarified that this is more an issue when using this library with Typescript:
```typescript
import * as Consul from 'consul'

const myConsul: Consul = new Consul({ port: '8500' })
myConsul.agent.service.register({ name: 'redis', port: 8500 })
```
Of course, passing either a number or string is fine if you're just using JS :).

I suggest maybe just updating the docs to clarify that port should be a number in both cases, and perhaps make the default port a number like you said?
