### ISSUE TITLE
Support Consul 1.0.0 HTTP verb breaking changes

### ISSUE THREAD

**Issue by eugeneduvenage** [silas/node-consul#64]
The release of Consul ver 1.0.0 has resulted in breaking changes to the allowed verbs for many API endpoints. e.g. agent/service/deregister MUST now be a PUT operation rather than a GET. A complete list of change can be found [in the 1.0.0 changelog](https://github.com/hashicorp/consul/blob/v1.0.0/CHANGELOG.md).
The current client is essentially unusable for the latest version of Consul. 

I'd be willing to submit a pull request to fix this if you could provide some guidance on how you would like backwards compatibility to be handled, I can't seem to see any way to know what version of server the client is talking to in order to decide on which verbs to use.

**Comment by eugeneduvenage** [comment]
I have modified all the affected routes to the correct verbs and tested on both consul 1.0.0, consul 0.9.3 and consul 0.9.2 and done some basic testing with my existing code base (which doesn't hit every single change) and I have had no problems so far. Would you be interested in a PR that just includes all the verb modifications as the change seems backward compatible.

**Comment by silas** [comment]
Sure, if you want to submit a PR I'll get it merged. I think we can just tell people to lock to an older version if something doesn't work.
