### ISSUE TITLE
About those PUT verbs...

### ISSUE THREAD

**Issue by ronkorving** [silas/node-consul#67]
Hi there,

I noticed you changed HTTP verbs to PUT. Will that break older versions of Consul or is it simply that Consul 1.0.0 has become strict about it where before it ignored the verb?

Only a minor version bump and nothing in the readme... I wonder if blindly upgrading `node-consul` would've gotten me into trouble or not (FWIW, I'm not using Consul 1.0.0 yet).

**Comment by christopherobin** [comment]
@ronkorving 

Consul 1.0.0 started enforcing verbs in their API, for example in `service/deregister`:

* __0.9.3__: https://github.com/hashicorp/consul/blob/v0.9.3/agent/agent_endpoint.go#L536-L551
* __1.0.0__: https://github.com/hashicorp/consul/blob/v1.0.0/agent/agent_endpoint.go#L607-L626

Previous versions didn't care about the verbs so it shouldn't break anything

**Comment by ronkorving** [comment]
Thanks! If @silas has anything to add, would love to hear it. Else I will close this issue.

**Comment by silas** [comment]
Nothing to add to what @christopherobin said, it's backwards compatible and fixes 1.x.

**Comment by ronkorving** [comment]
Thanks :)
