### ISSUE TITLE
Issue with register application in consul

### ISSUE THREAD

**Issue by sidnaik03** [silas/node-consul#69]
Hi,

I am using consul in node js. My code snippet is below
```
var consul = require('consul')({'host': config.CONSUL_IP_ADDRESS, 'port': config.CONSUL_PORT})

consul.agent.service.register({'name': config.SERVICE_NAME, 
  'id': config.SERVICE_ID, 'tags': config.TAGS, 
  'address': config.SERVICE_IP, 
  'port': config.SERVICE_PORT}, function (err) {
 if (err) {
    console.log('error in register')
    console.log(err)
   } else {
      console.log('error in success')
      console.log('sucess')
 }
});
```

I am getting below error:
> Failed to load resource: the server responded with a status of 400 (Bad Request)

> 

Kindly help me to resolve this issue

**Comment by silas** [comment]
I'd need to know what all the values of `config` passed to register were and the full `console.log` output. I assume you're already moved on, but if not feel free to re-open with the requested details.
