### ISSUE TITLE
Configurable retry intervals for watch

### ISSUE THREAD

**Issue by jdmarshall** [silas/node-consul#72]
The retry behavior of node-consul is overly aggressive in a clustered environment.

By the 1500 millisecond mark after a network issue we have already made 4 attempts to reconnect to Consul, per process/cluster worker.  This can easily spam a consul daemon if you have a larger cluster.  And if you aren't running a slave on localhost, you're really in trouble.

Instead of hard-coding an interval of 100, this should be a parameter with a default.

**Comment by silas** [comment]
Released to npm in `consul@0.31.0`
