### ISSUE TITLE
Timeout for watch does not respect Consul stagger

### ISSUE THREAD

**Issue by fox-hellraiser** [silas/node-consul#76]
Something wrong is happen here:

Issue: https://github.com/silas/node-consul/issues/51
Commit: https://github.com/silas/node-consul/commit/5f88dcc2a67cce84636ef9eb351c70170100ae85
Affected version: 0.33.0

```js
options.timeout = typeof options.timeout === 'number' ? 
    options.timeout :
    (utils.parseDuration(options.wait) + 500);
```
This code adds default timeout, based on "wait + 500 ms", if `timeout` config option is not specified.

From Consul docs: https://www.consul.io/api/index.html

> A small random amount of additional wait time is added to the supplied maximum wait time to spread out the wake up time of any concurrent requests. This adds up to wait / 16 additional time to the maximum duration.

So, if `timeout` is not set and `wait` specified as "60s", Consul adds random value from 0 to 3.75 secs, and this leads to random timeouts that emits `error` event:

```js
{ Error: consul: kv.get: request timed out (60500ms)
    at create (/hidden/node_modules/papi/lib/errors.js:14:5)
    at Object.timeout [as Timeout] (/hidden/node_modules/papi/lib/errors.js:62:15)
    at ClientRequest.<anonymous> (/hidden/node_modules/papi/lib/client.js:532:20)
    at emitNone (events.js:105:13)
    at ClientRequest.emit (events.js:207:7)
    at Timeout.<anonymous> (/hidden/node_modules/papi/lib/client.js:520:11)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5) isPapi: true, isTimeout: true }
```

Event `end` is this case not emitted.

This happens, because Consul timeout is, for example, 61 secs, but lib specify 60.5 secs and abort request before Consul.

Default timeout should calculated at least as "wait + wait/15" or "/14", and docs should clearly say some words about this pitfall.

**Comment by silas** [comment]
@fox-hellraiser Awesome, thanks for the great bug report and sorry for missing that.

How does https://github.com/silas/node-consul/pull/77 look as a solution?

**Comment by fox-hellraiser** [comment]
@silas thanks for the quick response. Looked at #77 PR, good solution.

**Comment by fox-hellraiser** [comment]
@silas great, thank you!
