### ISSUE TITLE
Connect to a HA consul

### ISSUE THREAD

**Issue by TinOo512** [silas/node-consul#79]
In an HA environment we will have multiple node (ex. `https://a.consul.mycompany.com:8500`, `https://b.consul.mycompany.com:8500`, ...). Because that library support only one host I'm wondering what's the best practice here?

- Should host support an array of nodes and we would need to maintains membership information in order to keep track of the master node?
- Use Fabio or other load balancer?
- Round robin DNS?
- Should we install the consul agent locally and use `https://localhost:8500` as endpoint.

Thanks!

**Comment by silas** [comment]
I've always used the local agent method.
