### ISSUE TITLE
Adding few helpful wrappers for thew lib

### ISSUE THREAD

**Issue by WoZ** [silas/node-consul#83]
Hello!

Me and my team are using consul in production for a few years. We developed few wrappers with clean  logic and fully deterministic behaviour. All of services are stateful and depends on `node-consul`. 

One of them is https://github.com/LCMApps/consul-kv-monitor.

The main ideas are:
- watch for changes like `consul.watch`
- retry to reconnect to consul agent on 4xx and 5xx errors while emitting `unhealthy` events and setting unhealthy state (it's must have for production usage to determine possibility to use data on partition of a network)
- distinguish fail on initial data fetch and fail in progress

Another product we are working on is leader elector that helps to elect only one instance to do some work, with control over sessions and kv. Just like consul leader election doc says.

Also we have https://github.com/LCMApps/consul-service-registrator but it ships without doc, so I will add info in few days or weeks.

I want to ask your opinion about integration of such services or at least mentioning them in the doc to help people to easily develop complex services.

Have a nice day!

**Comment by silas** [comment]
Hey WoZ, sorry for the late response. Those libraries look pretty cool and I'm definitely down to add references to the readme, although I'd prefer to keep higher level functionality out of this library.

If you want to respond with a bullet list in the format `* [Name](URL) - description` I'll add it to the readme.

**Comment by silas** [comment]
Feel free to re-open/comment if you want this added, otherwise closing for now.
