### ISSUE TITLE
KV directory structure access

### ISSUE THREAD

**Issue by Q-Angelo** [silas/node-consul#86]
The following is my directory structure：

![image](https://user-images.githubusercontent.com/17956058/60591167-713b9780-9dd0-11e9-8048-d8fbb539f51c.png)

What I expect is "consul.kv.get('develop/user/a')" access，Is there any way to access?

**Comment by silas** [comment]
The expected result of `consul.kv.get('develop/user/a')` would be a 404 error.

You're writing JSON as a value, so you'll need to read the entire JSON document back using `consul.kv.get('develop/user')`.

**Comment by Q-Angelo** [comment]
How do I perform a set operation？

```js
this.consul.kv.set('develop/user/a', '1')
```
Execute the above command, Become the following result:
![image](https://user-images.githubusercontent.com/17956058/60660151-b5d73980-9e89-11e9-9b9e-dc950086af49.png)

I want to modify one of the key values.
