### ISSUE TITLE
How do I perform a set operation？

### ISSUE THREAD

**Issue by Q-Angelo** [silas/node-consul#87]
How do I perform a set operation？

```js
this.consul.kv.set('develop/user/a', '1')
```
Execute the above command, Become the following result:
![image](https://user-images.githubusercontent.com/17956058/60660151-b5d73980-9e89-11e9-9b9e-dc950086af49.png)

I want to modify one of the key values.

**Comment by silas** [comment]
You should probably just create two keys and set values separately. If you want to modify a value in a json document, use `kv.get`, retrieve the value, decode the value as json, update the value, re-encode, and use `kv.set`.

[StackOverflow](http://stackoverflow.com) is a better place to get Consul (and general programming) help, I'd prefer to keep the issues sections for reporting problems with the node-consul library.

**Comment by Q-Angelo** [comment]
thank you!
