### ISSUE TITLE
Is any caching mechanism used in node-consul.

### ISSUE THREAD

**Issue by nakshay** [silas/node-consul#91]
@silas , is any caching mechanism used in this package to avoid hitting consul for every time? If not   then is there any plan to do it in future?

**Comment by silas** [comment]
I didn't have any plans to add caching functionality.

Have you seen caching functionality in other clients? I wasn't aware that anything in the Consul API was cacheable in a generic way.

**Comment by silas** [comment]
Feel free to re-open if you know of some api support for caching that you think should be implemented.
