### ISSUE TITLE
Session calls with ACL token

### ISSUE THREAD

**Issue by thechane** [silas/node-consul#92]
Hello,
First up - thanks for all the efforts here, I anticipate using this npm package I lot.

I'm struggling to get .session.create to work with ACLs configured, even when using the master token. Making the raw API calls myself seems fine so I'm confident all is well on the Consul side.

Error thrown is:
Error: rpc error making call: Permission denied

API body:
```
{
	"name": "_nrcontext/test",
	"node": "server1",
	"dc": "home"
}
```
Header:
X-Consul-Token: blah-blah-blah-blah

I am using promisify and HTTPS calls and have been able to successfully uses all the KV functions without any trouble.

**Comment by silas** [comment]
What version of node-consul and the consul server are you using?

It seems to be working for me using the latest version of both.

1) Start latest server

``` sh
$ docker run -p 8500:8500 --rm --name test-consul \
  -e 'CONSUL_LOCAL_CONFIG={"primary_datacenter":"dc1","acl":{"enabled":true,"default_policy":"deny","down_policy":"deny","tokens":{"master":"secret"}}}' \
  consul \
  consul agent -bootstrap -server -data-dir=/tmp -bind 127.0.0.1 -client=0.0.0.0 -ui -config-dir=/consul/config/local.json
```

2) Install latest node-consul

``` sh
$ npm install consul@0.35.0
```

3) Create session using token

``` javascript
const consul = require('consul')({ promisify: true });

consul.session.create({ token: 'secret' }).then(session => {
  console.log(session);
});
```

Or using token in defaults

``` javascript
const consul = require('consul')({ defaults: { token: 'secret' }, promisify: true });

consul.session.create().then(session => {
  console.log(session);
});
```

4) Results in the following

```
{ ID: '492ac851-381e-14e2-c337-9d1fdceb195a' }
```

**Comment by thechane** [comment]
Thanks for the clear explanation, I misunderstood how the defaults work. Classic case of coding too long without taking a break. Working as expected for me now.
